apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-tls
  namespace: envoy-gateway-system
spec:
  secretName: internal-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  dnsNames:
  - "*.internal.bakepyon.org"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-tls
  namespace: envoy-gateway-system
spec:
  secretName: external-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  dnsNames:
  - "*.bakepyon.org"
