---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-db-superuser
  namespace: blog-db
spec:
  encryptedData:
    password: AgDUDIwT3mAtjkIlLACX6DDqXQ4KbapO72NGvaukMMmZry6wLXSgQ8eQYfpXi0TO+7QJrdVz0hHvdG+1CEpFGmfPasitoabVYSv2QIcdwKA5HdLaqioTy13CjSC++aCjWf+FhfxE78y1pxGPG6oXukFgv7txoS5h8Byr1HT7tOkZJsmwTJyZT7DpBm7Nj0tfXZvloX3d2IG0WqkhWp4RYolBTGvmK7qKuWDaDvJjXiESxiGCVgx7XLQ+LhxxEohavh2XmQx9qJCYyO07vSqIQnoKJst1q8ip5QTsYrYgq6oKVr7aMbv+IgGSVp0Fai+AJFdkwEMWpvD8DUgRFnPEuyPBuUMeSCsrqI2y8z5JlXC/1shz7T31n5OuXjD5Ed5FJkMoRjlsJF2njwW2Tk/LTNinLlZ7h2r7NG1cfIfknhaR/0KiWAKSUq8cr/8lGo1MZAiZZV+hhRYvL+9w+LNjoHV1UQoQVxQuzcyS2oCgOYc5aBnrWa9rafvP9ecWB10Clw47GO+SlOoqiOJi9q8bohggUeiqJcbubPWz+/JCUKPyVvyPc1J9GaCTXcnd897xfQPrp2ZUdmRFJRDypNY+fC5Wn4Kh75j5WWuyxEAuNGJZr3ROuFD/AxCw+ckxu0p791tXDddmjxc4WyYMnOxq6imYR2YMVf3pShCcSYtrh5OHZrSl/kSY8BagcVt1WPjidO/vppZSTuP/js3gaYH4K6BAUDIC7AhyL88cNn5GDhMMvA==
    username: AgBS2TwWLPg02fyP7ZKfbr2DemiuOc821v7VemcrzJFnls/tiu2CNHXNGYii572sJ1+7Pzsvytof2GQxvnsmS+bJS03Mvdght7Z3lAhmOSRe/PjaHeZ96gzX/2a+g/7Kinz6Gyjn6E50Hl9y7mxvWh3uBmRy+vChGLPCKGTHikuWvkeMrG701SfrJI0YDLmkL0B+d6s3vccGL2/wx+oWitu5ncdRX6pv/i0lSjSnQKuodEwonF9f62Gpkw/+bo2v46USnLDl8rcJImCrV2h2/1kH4isWe81kj5Il+kdhmLGJ2BQE3knw9e69SJa7kiGWcvTpLlIoTHE2vgiZs+BKo1kYvAeYmX1I7ejjgLYamXW3/0/iNc/saiZ/vAqy/kes4s0ZdoA0K1IB95bajv2njbVMDFwptcAZZqzKfbd1HaYiPbG2vfdrdSNh+ff4LepXqS6gi4Z3oz5tkzy5ltIob4Nyi5lfe1ZKUtdciBaeJOdHoIdNKZmkC0VIHIfRg+poaicwEa7k+spa/H/RuR3cccFgZA493NqOkXZmjDixSLwoS+3y5jc7d49xO3isz0fbgyBY1fDQZTR2xHKu1kMxV9NPQJcm8TwHBTWlV7BE4Ot4jaVZ/dkGelT9Px7E5eFgztrNq/Nsr9wbATBElYQkUYXfn6dEMJiM9F0TrpnIC34VsYwkGt09fB0lz4G2QuPh05Hqt1AFaRpMlA==
  template:
    metadata:
      name: blog-db-superuser
      namespace: blog-db
