---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-db-app
  namespace: blog-db
spec:
  encryptedData:
    password: AgAVsyKzEYic6dE4BxIoPabl8HJDETJhzFmLkQfmVeyYDiGxNWqVQkomu6lSastJ14wyy/4tVEUgjHe7JKVyJvGWCcbyRcvvs+Lk9vfHkkn6Q9BKuAFsk3DMKhYQtp3+hMBrQ4gMr9Bvlyp75L68bx8XhOBMAzzf91rhs2Bc+24GR2gyLuNUfaP+3Jx3s5Rir2hFIVwp3GG0P9CCb5XMNsLcOaXKgXCphB8VqtoUwaalQoHqYuCd2jhuUy+aJvD3IUX2IAOapcY1I3Gd0BRY+EDoxsa2TXJAxDeSBl6Vu65378gqij5gxTJDFba8FKVjZy87NYBy1q5SCOA7meGDsiiff2VxiVOwb2TCMSDreidiToc2fIl9nTlcLw0dK6kDo61WzQEVhHdCdXct5Umr91/nOHFicGQ+Mgrgmo6jYCrs1y+30JDq8RgHpVl11wx+0257SeWQmCMlzsTwyMtPmUJCXEXa1DTv6ttxEAQaRUcj8PXgCQdixmcfAvBmzgHbGyxxgALaeCxY+/q+StdPheMgRntUoXGSKj1b1EWPSyZ0sR2rFyC38sUalVnlcCFK/vvHWVV4wubDDSIxqM1YZmV45S91xCAq/AHjeQwopLooyWQSOAHOjbsJ3CFM+wsQZ8Ctpx2cfPFL/i+3ULeA5GpsJMk+1QGeq0Riifx0gas/vJP+ZFmE9NVWKf6zncYq9NyCvG4LeXbjTMYuxx8FIUJLzvGHTcqK1yddxDoOjOTD0Q==
    username: AgCkG2LkvsWLuEi5b/w/PSOTNV00T/tfCCzAv4/3OS2EkTbL+A1/DvLRPdae3T8BGlmoK3M8W8NpOAnqnVRVtaP5JBDSnhMlaqvvxxMC0T/jEyLcx98+wQR7KMpIk2wX4NWv9kjX8zU8nKNS13zx+lzufcN3vDvVp+eitndC+YD8/61Mbdgz25YLhl7MuUo0j+5026CI2awKMc13njl31bkS0E+nlkT/joh4xjcY7dY3bw3mkCOhHaB7zPlvaRo30dTp8HXTPI6r8vOoOc6vvTy+AmGxxtMYgRj3SUMy1tAZmYjBHvbhxajtYzu9bcQOc8IJReq9MGJlVVSG47Bh3sym6cxx2EsN+eQ2EmUtcxq571z6uRtRzE2Ef4YtORlCY0fDEHf5o04TgkbQzix/Z63ZYza867jUPH7Mz3fwf3mKjOy/goToWOadUtBVEnKb6YFfTPvz9ExXwd8iVc/xPhTi3d4LivB3QSSTTMrpKCiDusqwPjp2bRRybR+rm+FpL0tXjEx1wCSAqJnLyTLKEqda6BetImtTDfPO5on8krZYSSMGIfdbbFWFXwJERRPoRmyCSmZrpT7Iok+zeJtoVt0bujH2DPAB3ANNkft/t0/LDhOwApgTy4bME5T3557NP0HkJK06KWYYcoK3UXxX9iY1mqc7Ix23CTg3KCoiW02WtGhbD/ZFEKPfd0qQr6GEgw9brze0
  template:
    metadata:
      name: blog-db-app
      namespace: blog-db
