apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: blog-db
  namespace: blog-db
spec:
  instances: 1
  bootstrap:
    initdb:
      database: blogdb
      owner: postgres
      secret:
        name: blog-db-app
  enableSuperuserAccess: true
  superuserSecret:
    name: blog-db-superuser
  storage:
    size: 10Gi          # 30Gi から縮小（Longhorn容量逼迫のため。詳細は調査履歴参照）
    storageClass: longhorn
  managed:
    services:
      additional:
        - selectorType: rw
          updateStrategy: patch
          serviceTemplate:
            metadata:
              name: blog-db-lb
              annotations:
                metallb.universe.tf/address-pool: internal-pool
            spec:
              type: LoadBalancer
  # plugins:
  #   - name: barman-cloud.cloudnative-pg.io
  #     enabled: true
  #     isWALArchiver: true
  #     parameters:
  #       barmanObjectName: blog-db-backup-store
