apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keiba-db
  namespace: keiba-db
spec:
  instances: 1
  bootstrap:
    initdb:
      database: pckeiba
      owner: postgres
      secret:
        name: keiba-db-app
  superuserSecret:
    name: keiba-db-superuser
  storage:
    size: 60Gi
    storageClass: longhorn
  managed:
    services:
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: keiba-db-lb
            annotations:
              metallb.universe.tf/address-pool: internal-pool
          spec:
            type: LoadBalancer