replicaCount: 1

image:
  repository: ghcr.io/project-zot/zot-linux-amd64
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000
  annotations:
    metallb.universe.tf/address-pool: internal-pool

persistence:
  enabled: true
  storageClass: longhorn
  size: 50Gi

configFiles:
  config.json: |-
    {
      "storage": {
        "rootDirectory": "/var/lib/registry"
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000"
      },
      "log": {
        "level": "info"
      }
    }

